### ISSUE TITLE
pojav crash

### ISSUE THREAD

**Issue by vantthinkofanameyet** [DGVPSH/SlackOpen#3]
when i open it in pojav it crashes on the main menu after the slack client loading thing
[latestlog.txt](https://github.com/user-attachments/files/17689013/latestlog.txt)

**Comment by vantthinkofanameyet** [comment]
...

**Comment by vantthinkofanameyet** [comment]
.

**Comment by vantthinkofanameyet** [comment]
its been 2 weeks will someone even respond

**Comment by catInfinite** [comment]
maybe you should get a pc instead

**Comment by notamudkipiguess** [comment]
Try glow worm, since has more render options i assume the effects on the title screen are causing holy gl4es to just freak out and crash:
https://github.com/Vera-Firefly/Pojav-Glow-Worm

**Comment by notamudkipiguess** [comment]
VGPU + Internal-11 runtime seems to work on most clients like SigmaNG. Haven't tried Slack yet tho.

**Comment by notamudkipiguess** [comment]
im starting to think this client is a rat because not a single render and runtime combo got past the title screen
